### ISSUE TITLE
awk error

### ISSUE THREAD

**Issue by ppKrauss** [gibson042/canonicaljson-spec#1]
Hi, a "standard pretty JSON" is very important, as "easy diff" and "universal human-readability", so  *canonicalJSON + prettyjson* is a good solution, even for [digital preservation](https://en.wikipedia.org/wiki/Digital_preservation).

Using `chmod 777 prettyjson.awk` and `./prettyjson.awk file.json` at UBUNTU 16 LTS, it is causing error
 *"awk: run time error: regular expression compile failed (missing operand)"*.

-----

PS: a complement for *prettyjson* is, for *checksums*, to pipe with some `stripSpaces.awk`  before hash  generation.

**Comment by gibson042** [comment]
Thanks for the report; I've confirmed the awk incompatibility and am fixing it now.
