### ISSUE TITLE
Discuss additional prior art

### ISSUE THREAD

**Issue by jonasfj** [gibson042/canonicaljson-spec#2]
See: http://wiki.laptop.org/go/Canonical_JSON

I noticed that this is used by [the update framework](https://github.com/theupdateframework/specification/blob/master/tuf-spec.md#4-document-formats).

I suspect it might be relevant to mention.

----
It might be nice to discuss how this differs from the various other formats. From what I can see the one above mostly differs in that it allows any bytes as strings, where as this spec only allows utf8 (and allows floats), similarly the keybase spec seems similar except they only allow printable ascii keys.

**Comment by gibson042** [comment]
Thanks, done at f3272fc87cbe6a0c1c43523ed32632b140e02995.
