### ISSUE TITLE
Additional prior art

### ISSUE THREAD

**Issue by matrey** [gibson042/canonicaljson-spec#4]
https://matrix.org/docs/spec/appendices.html#canonical-json
https://github.com/matrix-org/python-canonicaljson
https://github.com/matrix-org/python-canonicaljson/issues/16  "We have a similar module in some of our project at Mozilla but would be happy to use yours instead of our own"

I'm not sure how it compare with this project ; prior art? (accidental) implementation?

**Comment by gibson042** [comment]
The matrix.org spec appears to be incomplete with respect to unpaired surrogates and non-integer numbers, and the python one doesn't include a spec at all. I don't think it's necessary to reference either, but a pull request would be accepted.
